import { Injectable, signal } from '@angular/core';
import { Hour } from './hour';
import { Summary } from './summary';

@Injectable({
  providedIn: 'root',
})
export class HourlyDataService {
  readonly rowData = signal<(Hour | Summary)[]>([
    {
      id: 0,
      godzina: '0-1',
      oczekiwaneWizyty: 3.23,
      liczbaPielegniarek: 4,
      wydajnoscPielegniarek: 5.05,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 5.05,
      mozliwoscPokryciaZopatrzenia: '',
    },
    {
      id: 1,
      godzina: '1-2',
      oczekiwaneWizyty: 2.39,
      liczbaPielegniarek: 4,
      wydajnoscPielegniarek: 5.05,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 5.05,
      mozliwoscPokryciaZopatrzenia: '',
    },
    {
      id: 2,
      godzina: '2-3',
      oczekiwaneWizyty: 2.14,
      liczbaPielegniarek: 4,
      wydajnoscPielegniarek: 5.05,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 5.05,
      mozliwoscPokryciaZopatrzenia: '',
    },
    {
      id: 3,
      godzina: '3-4',
      oczekiwaneWizyty: 1.83,
      liczbaPielegniarek: 4,
      wydajnoscPielegniarek: 5.05,
      liczbaLekarzy: 8,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 5.05,
      mozliwoscPokryciaZopatrzenia: '',
    },
    {
      id: 4,
      godzina: '4-5',
      oczekiwaneWizyty: 1.7,
      liczbaPielegniarek: 4,
      wydajnoscPielegniarek: 5.05,
      liczbaLekarzy: 8,
      wydajnoscLekarzy: 10.99,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 5.05,
      mozliwoscPokryciaZopatrzenia: '',
    },
    {
      id: 5,
      godzina: '5-6',
      oczekiwaneWizyty: 1.67,
      liczbaPielegniarek: 4,
      wydajnoscPielegniarek: 5.05,
      liczbaLekarzy: 8,
      wydajnoscLekarzy: 10.99,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 5.05,
      mozliwoscPokryciaZopatrzenia: '',
    },
    {
      id: 6,
      godzina: '6-7',
      oczekiwaneWizyty: 1.8,
      liczbaPielegniarek: 4,
      wydajnoscPielegniarek: 5.05,
      liczbaLekarzy: 8,
      wydajnoscLekarzy: 10.99,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 5.05,
      mozliwoscPokryciaZopatrzenia: '',
    },
    {
      id: 7,
      godzina: '7-8',
      oczekiwaneWizyty: 2.96,
      liczbaPielegniarek: 7,
      wydajnoscPielegniarek: 5.05,
      liczbaLekarzy: 8,
      wydajnoscLekarzy: 10.99,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 5.05,
      mozliwoscPokryciaZopatrzenia: '',
    },
    {
      id: 8,
      godzina: '8-9',
      oczekiwaneWizyty: 5.66,
      liczbaPielegniarek: 7,
      wydajnoscPielegniarek: 8.84,
      liczbaLekarzy: 8,
      wydajnoscLekarzy: 10.99,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 8.84,
      mozliwoscPokryciaZopatrzenia: '',
    },
    {
      id: 9,
      godzina: '9-10',
      oczekiwaneWizyty: 9.25,
      liczbaPielegniarek: 7,
      wydajnoscPielegniarek: 8.84,
      liczbaLekarzy: 8,
      wydajnoscLekarzy: 10.99,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 8.84,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 10,
      godzina: '10-11',
      oczekiwaneWizyty: 12.15,
      liczbaPielegniarek: 7,
      wydajnoscPielegniarek: 8.84,
      liczbaLekarzy: 8,
      wydajnoscLekarzy: 10.99,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 8.84,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 11,
      godzina: '11-12',
      oczekiwaneWizyty: 13.25,
      liczbaPielegniarek: 7,
      wydajnoscPielegniarek: 8.84,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 10.99,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 8.84,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 12,
      godzina: '12-13',
      oczekiwaneWizyty: 12.25,
      liczbaPielegniarek: 7,
      wydajnoscPielegniarek: 8.84,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Lekarze',
      waskaWydajnosc: 8.24,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 13,
      godzina: '13-14',
      oczekiwaneWizyty: 10.52,
      liczbaPielegniarek: 7,
      wydajnoscPielegniarek: 8.84,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Lekarze',
      waskaWydajnosc: 8.24,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 14,
      godzina: '14-15',
      oczekiwaneWizyty: 9.44,
      liczbaPielegniarek: 7,
      wydajnoscPielegniarek: 8.84,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Lekarze',
      waskaWydajnosc: 8.24,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 15,
      godzina: '15-16',
      oczekiwaneWizyty: 9.73,
      liczbaPielegniarek: 7,
      wydajnoscPielegniarek: 8.84,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Lekarze',
      waskaWydajnosc: 8.24,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 16,
      godzina: '16-17',
      oczekiwaneWizyty: 10.29,
      liczbaPielegniarek: 7,
      wydajnoscPielegniarek: 8.84,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Lekarze',
      waskaWydajnosc: 8.24,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 17,
      godzina: '17-18',
      oczekiwaneWizyty: 10.1,
      liczbaPielegniarek: 7,
      wydajnoscPielegniarek: 8.84,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Lekarze',
      waskaWydajnosc: 8.24,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 18,
      godzina: '18-19',
      oczekiwaneWizyty: 9.34,
      liczbaPielegniarek: 7,
      wydajnoscPielegniarek: 8.84,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Lekarze',
      waskaWydajnosc: 8.24,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 19,
      godzina: '19-20',
      oczekiwaneWizyty: 8.57,
      liczbaPielegniarek: 4,
      wydajnoscPielegniarek: 8.84,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Lekarze',
      waskaWydajnosc: 8.24,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 20,
      godzina: '20-21',
      oczekiwaneWizyty: 7.61,
      liczbaPielegniarek: 4,
      wydajnoscPielegniarek: 5.05,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 5.05,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 21,
      godzina: '21-22',
      oczekiwaneWizyty: 6.33,
      liczbaPielegniarek: 4,
      wydajnoscPielegniarek: 5.05,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 5.05,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 22,
      godzina: '22-23',
      oczekiwaneWizyty: 5.08,
      liczbaPielegniarek: 4,
      wydajnoscPielegniarek: 5.05,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 5.05,
      mozliwoscPokryciaZopatrzenia: 'Niedobor wydajn',
    },
    {
      id: 23,
      godzina: '23-24',
      oczekiwaneWizyty: 4.08,
      liczbaPielegniarek: 4,
      wydajnoscPielegniarek: 5.05,
      liczbaLekarzy: 6,
      wydajnoscLekarzy: 8.24,
      liczbaLozek: 50,
      wydajnoscLozek: 12.18,
      liczbaLozekObserwacja: 15.0,
      wydajnoscLozekObserwacja: 11.36,
      waskiZasob: 'Pielegn',
      waskaWydajnosc: 5.05,
      mozliwoscPokryciaZopatrzenia: '',
    },
    {
      id: 24,
      godzina: 'Zapotrz./dobę',
      oczekiwaneWizyty: 161.35,
      liczbaPielegniarek: 777,
      wydajnoscPielegniarek: 166.61,
      liczbaLekarzy: 777,
      wydajnoscLekarzy: 219.84,
      liczbaLozek: 777,
      wydajnoscLozek: 292.35,
      liczbaLozekObserwacja: 777,
      wydajnoscLozekObserwacja: 272.73,
      waskiZasob: '',
      waskaWydajnosc: 777,
      mozliwoscPokryciaZopatrzenia: '',
    } as Summary,
    {
      id: 25,
      godzina: '',
      oczekiwaneWizyty: 777,
      liczbaPielegniarek: 777,
      wydajnoscPielegniarek: 0.9684,
      liczbaLekarzy: 777,
      wydajnoscLekarzy: 0.7339,
      liczbaLozek: 777,
      wydajnoscLozek: 0.5519,
      liczbaLozekObserwacja: 777,
      wydajnoscLozekObserwacja: 0.5916,
      waskiZasob: '',
      waskaWydajnosc: 777,
      mozliwoscPokryciaZopatrzenia: '',
    } as Summary,
  ]);

  constructor() {}
}
